paths:
  raw_data: data/raw
  processed_data: data/processed
  models_dir: outdata/models
  vectors_dir: outdata/vectors
  image_dir: outdata/images
  logs_dir: data/logs
  scripts: scripts

recommender_nn:
  batch_size: 256
  num_epochs: 20
  learning_rate: 0.001
  patience: 5
  hidden_dim: 128
